CREATE TABLE `experiences` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(128) NOT NULL,
	`name` varchar(256) NOT NULL,
	`category` enum('tour','hiking','culture','sport','wellness','family','adventure') NOT NULL,
	`description` text,
	`shortDescription` text,
	`duration` varchar(64),
	`price` varchar(64),
	`difficulty` enum('easy','moderate','difficult'),
	`location` varchar(256),
	`meetingPoint` varchar(256),
	`phone` varchar(32),
	`email` varchar(320),
	`website` varchar(512),
	`imageUrl` varchar(512),
	`familyFriendly` boolean DEFAULT false,
	`wheelchairAccessible` boolean DEFAULT false,
	`seasonalAvailability` varchar(128),
	`minParticipants` int,
	`maxParticipants` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `experiences_id` PRIMARY KEY(`id`),
	CONSTRAINT `experiences_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `hotels` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(128) NOT NULL,
	`name` varchar(256) NOT NULL,
	`type` enum('hotel','hostel','pension','apartment') NOT NULL DEFAULT 'hotel',
	`stars` int,
	`address` varchar(512) NOT NULL,
	`postalCode` varchar(10) NOT NULL,
	`city` varchar(128) NOT NULL,
	`description` text,
	`shortDescription` text,
	`phone` varchar(32),
	`email` varchar(320),
	`website` varchar(512),
	`imageUrl` varchar(512),
	`priceRange` varchar(64),
	`amenities` json,
	`petsAllowed` boolean DEFAULT false,
	`familyFriendly` boolean DEFAULT false,
	`wheelchairAccessible` boolean DEFAULT false,
	`parking` boolean DEFAULT false,
	`wifi` boolean DEFAULT true,
	`breakfast` boolean DEFAULT false,
	`restaurant` boolean DEFAULT false,
	`spa` boolean DEFAULT false,
	`latitude` varchar(32),
	`longitude` varchar(32),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `hotels_id` PRIMARY KEY(`id`),
	CONSTRAINT `hotels_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `restaurants` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(128) NOT NULL,
	`name` varchar(256) NOT NULL,
	`cuisineType` varchar(128),
	`address` varchar(512) NOT NULL,
	`postalCode` varchar(10) NOT NULL,
	`city` varchar(128) NOT NULL,
	`description` text,
	`phone` varchar(32),
	`email` varchar(320),
	`website` varchar(512),
	`imageUrl` varchar(512),
	`priceLevel` enum('budget','moderate','upscale','fine_dining'),
	`openingHours` text,
	`vegetarianOptions` boolean DEFAULT false,
	`veganOptions` boolean DEFAULT false,
	`glutenFreeOptions` boolean DEFAULT false,
	`outdoorSeating` boolean DEFAULT false,
	`reservationRequired` boolean DEFAULT false,
	`latitude` varchar(32),
	`longitude` varchar(32),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `restaurants_id` PRIMARY KEY(`id`),
	CONSTRAINT `restaurants_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
ALTER TABLE `users` MODIFY COLUMN `role` enum('user','admin','hotelier') NOT NULL DEFAULT 'user';