CREATE TABLE `hotels` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(200) NOT NULL,
	`slug` varchar(200) NOT NULL,
	`stars` int,
	`category` varchar(100),
	`address` varchar(300),
	`city` varchar(100) DEFAULT 'Chur',
	`postalCode` varchar(10),
	`country` varchar(50) DEFAULT 'Schweiz',
	`phone` varchar(50),
	`email` varchar(320),
	`website` varchar(500),
	`bookingUrl` varchar(500),
	`latitude` decimal(10,7),
	`longitude` decimal(10,7),
	`descriptionDe` text,
	`descriptionEn` text,
	`shortDescDe` text,
	`shortDescEn` text,
	`priceFrom` int,
	`priceTo` int,
	`currency` varchar(10) DEFAULT 'CHF',
	`checkInFrom` varchar(10),
	`checkInTo` varchar(10),
	`checkOutFrom` varchar(10),
	`checkOutTo` varchar(10),
	`wifiFree` boolean DEFAULT false,
	`parkingFree` boolean DEFAULT false,
	`parkingPaid` boolean DEFAULT false,
	`breakfastIncluded` boolean DEFAULT false,
	`petsAllowed` boolean DEFAULT false,
	`petSurcharge` varchar(100),
	`familyFriendly` boolean DEFAULT false,
	`wheelchairAccessible` boolean DEFAULT false,
	`elevator` boolean DEFAULT false,
	`spa` boolean DEFAULT false,
	`pool` boolean DEFAULT false,
	`gym` boolean DEFAULT false,
	`restaurant` boolean DEFAULT false,
	`bar` boolean DEFAULT false,
	`roomService` boolean DEFAULT false,
	`airConditioning` boolean DEFAULT false,
	`balcony` boolean DEFAULT false,
	`mainImage` varchar(500),
	`galleryImages` json,
	`specialFeatures` text,
	`isPublished` boolean NOT NULL DEFAULT true,
	`isFeatured` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `hotels_id` PRIMARY KEY(`id`),
	CONSTRAINT `hotels_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `providers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`username` varchar(100) NOT NULL,
	`passwordHash` varchar(255) NOT NULL,
	`displayName` varchar(200),
	`email` varchar(320),
	`role` enum('admin','hotelier','gastronom') NOT NULL DEFAULT 'hotelier',
	`linkedHotelId` int,
	`linkedRestaurantId` int,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `providers_id` PRIMARY KEY(`id`),
	CONSTRAINT `providers_username_unique` UNIQUE(`username`)
);
--> statement-breakpoint
CREATE TABLE `restaurants` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(200) NOT NULL,
	`slug` varchar(200) NOT NULL,
	`address` varchar(300),
	`city` varchar(100) DEFAULT 'Chur',
	`postalCode` varchar(10),
	`country` varchar(50) DEFAULT 'Schweiz',
	`phone` varchar(50),
	`email` varchar(320),
	`website` varchar(500),
	`menuUrl` varchar(500),
	`latitude` decimal(10,7),
	`longitude` decimal(10,7),
	`cuisineTypes` json,
	`priceLevel` varchar(20),
	`ambiance` varchar(200),
	`descriptionDe` text,
	`descriptionEn` text,
	`shortDescDe` text,
	`shortDescEn` text,
	`openingHours` json,
	`openingHoursText` text,
	`closedDays` json,
	`outdoorSeating` boolean DEFAULT false,
	`terrace` boolean DEFAULT false,
	`garden` boolean DEFAULT false,
	`wheelchairAccessible` boolean DEFAULT false,
	`vegetarianOptions` boolean DEFAULT false,
	`veganOptions` boolean DEFAULT false,
	`glutenFreeOptions` boolean DEFAULT false,
	`reservationRequired` boolean DEFAULT false,
	`reservationUrl` varchar(500),
	`mainImage` varchar(500),
	`galleryImages` json,
	`isPublished` boolean NOT NULL DEFAULT true,
	`isFeatured` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `restaurants_id` PRIMARY KEY(`id`),
	CONSTRAINT `restaurants_slug_unique` UNIQUE(`slug`)
);
