/**
 * Seed-Skript: Wird beim Server-Start ausgeführt, wenn die Tabellen leer sind.
 * Erstellt den Admin-Account und füllt Hotels + Restaurants mit Daten.
 */
import bcrypt from "bcryptjs";
import { eq, sql } from "drizzle-orm";
import { getDb } from "./db";
import { providers, hotels, restaurants } from "../drizzle/schema";

const ADMIN_USERNAME = "admin";
const ADMIN_DEFAULT_PASSWORD = "SmartStay2026!";

export async function runSeed() {
  const db = await getDb();
  if (!db) {
    console.log("[Seed] Datenbank nicht verfügbar – Seed übersprungen");
    return;
  }

  try {
    // 1. Admin-Account erstellen (falls nicht vorhanden)
    const existingAdmin = await db.select().from(providers).where(eq(providers.username, ADMIN_USERNAME)).limit(1);
    if (existingAdmin.length === 0) {
      const hash = await bcrypt.hash(ADMIN_DEFAULT_PASSWORD, 10);
      await db.insert(providers).values({
        username: ADMIN_USERNAME,
        passwordHash: hash,
        displayName: "Administrator",
        role: "admin",
        isActive: true,
      });
      console.log("[Seed] Admin-Account erstellt (admin / SmartStay2026!)");
    } else {
      console.log("[Seed] Admin-Account existiert bereits");
    }

    // 2. Hotels seeden (falls leer)
    const hotelCount = await db.select({ count: sql<number>`count(*)` }).from(hotels);
    if (Number(hotelCount[0]?.count) === 0) {
      console.log("[Seed] Hotels einfügen...");
      await seedHotels(db);
    } else {
      console.log(`[Seed] ${hotelCount[0]?.count} Hotels bereits vorhanden`);
    }

    // 3. Restaurants seeden (falls leer)
    const restCount = await db.select({ count: sql<number>`count(*)` }).from(restaurants);
    if (Number(restCount[0]?.count) === 0) {
      console.log("[Seed] Restaurants einfügen...");
      await seedRestaurants(db);
    } else {
      console.log(`[Seed] ${restCount[0]?.count} Restaurants bereits vorhanden`);
    }

    console.log("[Seed] Abgeschlossen");
  } catch (error) {
    console.error("[Seed] Fehler:", error);
  }
}

async function seedHotels(db: any) {
  const hotelData = [
    {
      name: "Romantik Hotel Stern",
      slug: "romantik-hotel-stern",
      stars: 4,
      category: "Romantik Hotel",
      address: "Reichsgasse 11",
      city: "Chur",
      postalCode: "7000",
      phone: "+41 81 258 57 57",
      email: "info@stern-chur.ch",
      website: "https://www.stern-chur.ch",
      descriptionDe: "Das Romantik Hotel Stern ist das älteste Gasthaus in Chur und verbindet historischen Charme mit modernem Komfort. Im Herzen der Altstadt gelegen, bietet es individuell gestaltete Zimmer und ein preisgekröntes Restaurant.",
      shortDescDe: "Historisches Boutique-Hotel im Herzen der Churer Altstadt",
      priceFrom: 180,
      priceTo: 380,
      checkInFrom: "14:00",
      checkInTo: "22:00",
      checkOutFrom: "07:00",
      checkOutTo: "11:00",
      wifiFree: true,
      breakfastIncluded: true,
      restaurant: true,
      bar: true,
      wheelchairAccessible: false,
      elevator: false,
      isPublished: true,
      isFeatured: true,
    },
    {
      name: "Hotel ABC",
      slug: "hotel-abc",
      stars: 3,
      category: "Stadthotel",
      address: "Ottostrasse 8",
      city: "Chur",
      postalCode: "7000",
      phone: "+41 81 258 58 58",
      email: "info@hotel-abc-chur.ch",
      website: "https://www.hotel-abc-chur.ch",
      descriptionDe: "Das Hotel ABC liegt zentral in Chur und bietet komfortable Zimmer zu fairen Preisen. Ideal für Geschäftsreisende und Städteurlauber.",
      shortDescDe: "Komfortables Stadthotel mit zentraler Lage",
      priceFrom: 120,
      priceTo: 220,
      checkInFrom: "14:00",
      checkInTo: "23:00",
      checkOutFrom: "07:00",
      checkOutTo: "11:00",
      wifiFree: true,
      parkingPaid: true,
      breakfastIncluded: true,
      elevator: true,
      isPublished: true,
      isFeatured: false,
    },
    {
      name: "Hotel Chur",
      slug: "hotel-chur",
      stars: 4,
      category: "Stadthotel",
      address: "Welschdörfli 2",
      city: "Chur",
      postalCode: "7000",
      phone: "+41 81 255 55 55",
      email: "info@hotelchur.ch",
      website: "https://www.hotelchur.ch",
      descriptionDe: "Das Hotel Chur bietet moderne Zimmer in unmittelbarer Nähe zum Bahnhof. Perfekt für Reisende, die Chur und Graubünden entdecken möchten.",
      shortDescDe: "Modernes Hotel direkt beim Bahnhof Chur",
      priceFrom: 150,
      priceTo: 300,
      checkInFrom: "15:00",
      checkInTo: "22:00",
      checkOutFrom: "07:00",
      checkOutTo: "11:00",
      wifiFree: true,
      parkingPaid: true,
      breakfastIncluded: true,
      elevator: true,
      airConditioning: true,
      gym: true,
      isPublished: true,
      isFeatured: true,
    },
    {
      name: "Ambiente Hotel & Restaurant Freieck",
      slug: "ambiente-hotel-freieck",
      stars: 3,
      category: "Boutique Hotel",
      address: "Reichsgasse 44",
      city: "Chur",
      postalCode: "7000",
      phone: "+41 81 255 15 15",
      email: "info@freieck.ch",
      website: "https://www.freieck.ch",
      descriptionDe: "Das Ambiente Hotel Freieck liegt mitten in der historischen Altstadt von Chur. Das Boutique-Hotel besticht durch seinen einzigartigen Charme und die persönliche Atmosphäre.",
      shortDescDe: "Charmantes Boutique-Hotel in der Altstadt",
      priceFrom: 130,
      priceTo: 250,
      checkInFrom: "14:00",
      checkInTo: "22:00",
      checkOutFrom: "07:00",
      checkOutTo: "10:30",
      wifiFree: true,
      restaurant: true,
      bar: true,
      isPublished: true,
      isFeatured: false,
    },
    {
      name: "Hotel Drei Könige",
      slug: "hotel-drei-koenige",
      stars: 3,
      category: "Traditionshotel",
      address: "Reichsgasse 18",
      city: "Chur",
      postalCode: "7000",
      phone: "+41 81 252 17 25",
      email: "info@dreikoenige-chur.ch",
      website: "https://www.dreikoenige-chur.ch",
      descriptionDe: "Das Hotel Drei Könige ist ein traditionsreiches Haus in der Churer Altstadt. Es bietet gemütliche Zimmer und ein beliebtes Restaurant mit Bündner Spezialitäten.",
      shortDescDe: "Traditionsreiches Hotel mit Bündner Küche",
      priceFrom: 110,
      priceTo: 200,
      checkInFrom: "14:00",
      checkInTo: "22:00",
      checkOutFrom: "07:00",
      checkOutTo: "11:00",
      wifiFree: true,
      restaurant: true,
      petsAllowed: true,
      petSurcharge: "CHF 20 pro Nacht",
      isPublished: true,
      isFeatured: false,
    },
    {
      name: "HOTEL & GASTHAUS MARSÖL",
      slug: "hotel-marsoel",
      stars: 3,
      category: "Gasthaus",
      address: "Süsswinkelgasse 25",
      city: "Chur",
      postalCode: "7000",
      phone: "+41 81 252 97 68",
      email: "info@marsoel.ch",
      website: "https://www.marsoel.ch",
      descriptionDe: "Das Hotel Marsöl bietet eine familiäre Atmosphäre und liegt in einer ruhigen Gasse der Churer Altstadt. Bekannt für seine herzliche Gastfreundschaft und die gutbürgerliche Küche.",
      shortDescDe: "Familiäres Gasthaus in ruhiger Altstadtlage",
      priceFrom: 100,
      priceTo: 180,
      checkInFrom: "14:00",
      checkInTo: "21:00",
      checkOutFrom: "07:30",
      checkOutTo: "10:00",
      wifiFree: true,
      restaurant: true,
      isPublished: true,
      isFeatured: false,
    },
    {
      name: "Ibis Budget Chur",
      slug: "ibis-budget-chur",
      stars: 2,
      category: "Budget Hotel",
      address: "Comercialstrasse 32",
      city: "Chur",
      postalCode: "7000",
      phone: "+41 81 544 04 04",
      email: "info@ibis-chur.ch",
      website: "https://all.accor.com",
      descriptionDe: "Das ibis budget Chur bietet moderne, funktionale Zimmer zu günstigen Preisen. Ideal für preisbewusste Reisende.",
      shortDescDe: "Modernes Budget-Hotel für preisbewusste Reisende",
      priceFrom: 79,
      priceTo: 130,
      checkInFrom: "14:00",
      checkInTo: "23:59",
      checkOutFrom: "06:00",
      checkOutTo: "10:00",
      wifiFree: true,
      parkingPaid: true,
      elevator: true,
      airConditioning: true,
      isPublished: true,
      isFeatured: false,
    },
    {
      name: "Zunfthaus zur Rebleuten",
      slug: "zunfthaus-rebleuten",
      stars: 3,
      category: "Historisches Gasthaus",
      address: "Pfisterplatz 1",
      city: "Chur",
      postalCode: "7000",
      phone: "+41 81 255 11 44",
      email: "info@rebleuten.ch",
      website: "https://www.rebleuten.ch",
      descriptionDe: "Das Zunfthaus zur Rebleuten ist ein historisches Gebäude am Pfisterplatz. Es bietet stilvoll eingerichtete Zimmer und ein Restaurant mit regionaler Küche.",
      shortDescDe: "Historisches Zunfthaus mit stilvollem Ambiente",
      priceFrom: 140,
      priceTo: 260,
      checkInFrom: "14:00",
      checkInTo: "22:00",
      checkOutFrom: "07:00",
      checkOutTo: "11:00",
      wifiFree: true,
      restaurant: true,
      bar: true,
      isPublished: true,
      isFeatured: false,
    },
  ];

  for (const hotel of hotelData) {
    await db.insert(hotels).values(hotel);
  }
  console.log(`[Seed] ${hotelData.length} Hotels eingefügt`);
}

async function seedRestaurants(db: any) {
  const restaurantData = [
    {
      name: "Restaurant Calanda",
      slug: "restaurant-calanda",
      address: "Poststrasse 14",
      city: "Chur",
      postalCode: "7000",
      phone: "+41 81 252 11 42",
      email: "info@calanda-chur.ch",
      website: "https://www.calanda-chur.ch",
      cuisineTypes: (["Schweizerisch", "Bündner Spezialitäten"]),
      priceLevel: "$$",
      descriptionDe: "Das Restaurant Calanda serviert traditionelle Bündner Küche in gemütlichem Ambiente. Bekannt für Capuns, Pizokel und Bündner Gerstensuppe.",
      shortDescDe: "Traditionelle Bündner Küche im Herzen von Chur",
      openingHours: ({
        monday: { open: "11:30", close: "14:00" },
        tuesday: { open: "11:30", close: "14:00" },
        wednesday: { open: "11:30", close: "14:00" },
        thursday: { open: "11:30", close: "14:00" },
        friday: { open: "11:30", close: "14:00" },
        saturday: { open: "11:30", close: "14:00" },
      }),
      closedDays: (["sunday"]),
      openingHoursText: "Warme Küche 11:30-14:00 und 17:30-21:30",
      vegetarianOptions: true,
      outdoorSeating: true,
      terrace: true,
      menuUrl: "https://www.calanda-chur.ch/menu",
      isPublished: true,
      isFeatured: true,
    },
    {
      name: "Brasserie Süsswinkel",
      slug: "brasserie-suesswinkel",
      address: "Süsswinkelgasse 6",
      city: "Chur",
      postalCode: "7000",
      phone: "+41 81 253 12 12",
      website: "https://www.suesswinkel.ch",
      cuisineTypes: (["International", "Schweizerisch"]),
      priceLevel: "$$",
      descriptionDe: "Die Brasserie Süsswinkel bietet internationale und schweizerische Küche in stilvollem Ambiente in der Churer Altstadt.",
      shortDescDe: "Stilvolle Brasserie in der Altstadt",
      openingHours: ({
        tuesday: { open: "11:00", close: "23:00" },
        wednesday: { open: "11:00", close: "23:00" },
        thursday: { open: "11:00", close: "23:00" },
        friday: { open: "11:00", close: "23:30" },
        saturday: { open: "11:00", close: "23:30" },
        sunday: { open: "11:00", close: "22:00" },
      }),
      closedDays: (["monday"]),
      vegetarianOptions: true,
      veganOptions: true,
      outdoorSeating: true,
      menuUrl: "https://www.suesswinkel.ch/speisekarte",
      isPublished: true,
      isFeatured: true,
    },
    {
      name: "Veltliner Weinstube",
      slug: "veltliner-weinstube",
      address: "Kirchgasse 18",
      city: "Chur",
      postalCode: "7000",
      phone: "+41 81 252 40 63",
      website: "https://www.veltliner-weinstube.ch",
      cuisineTypes: (["Schweizerisch", "Bündner Spezialitäten", "Italienisch"]),
      priceLevel: "$$",
      descriptionDe: "Die Veltliner Weinstube ist eine der ältesten Weinstuben in Chur. Bekannt für hervorragende Weine und traditionelle Bündner Gerichte.",
      shortDescDe: "Historische Weinstube mit Bündner Spezialitäten",
      openingHours: ({
        monday: { open: "10:00", close: "23:30" },
        tuesday: { open: "10:00", close: "23:30" },
        wednesday: { open: "10:00", close: "23:30" },
        thursday: { open: "10:00", close: "23:30" },
        friday: { open: "10:00", close: "00:00" },
        saturday: { open: "10:00", close: "00:00" },
      }),
      closedDays: (["sunday"]),
      vegetarianOptions: true,
      outdoorSeating: true,
      terrace: true,
      menuUrl: "https://www.veltliner-weinstube.ch/speisekarte",
      isPublished: true,
      isFeatured: true,
    },
    {
      name: "Ristorante Tre Fratelli",
      slug: "ristorante-tre-fratelli",
      address: "Steinbruchstrasse 2",
      city: "Chur",
      postalCode: "7000",
      phone: "+41 81 253 44 55",
      cuisineTypes: (["Italienisch", "Pizza"]),
      priceLevel: "$$",
      descriptionDe: "Authentische italienische Küche mit frischer Pasta, Pizza aus dem Holzofen und einer grossen Auswahl an italienischen Weinen.",
      shortDescDe: "Authentische italienische Küche mit Holzofenpizza",
      openingHours: ({
        monday: { open: "11:00", close: "14:00" },
        tuesday: { open: "11:00", close: "14:00" },
        wednesday: { open: "11:00", close: "14:00" },
        thursday: { open: "11:00", close: "14:00" },
        friday: { open: "11:00", close: "14:00" },
        saturday: { open: "11:00", close: "22:00" },
      }),
      closedDays: (["sunday"]),
      openingHoursText: "Abends Di-Sa 17:30-22:00",
      vegetarianOptions: true,
      veganOptions: true,
      isPublished: true,
      isFeatured: false,
    },
    {
      name: "Thai Garden",
      slug: "thai-garden",
      address: "Grabenstrasse 38",
      city: "Chur",
      postalCode: "7000",
      phone: "+41 81 252 88 88",
      cuisineTypes: (["Asiatisch", "Thailändisch"]),
      priceLevel: "$$",
      descriptionDe: "Das Thai Garden bietet authentische thailändische Küche mit frischen Zutaten. Von Pad Thai bis Green Curry – hier schmeckt Thailand.",
      shortDescDe: "Authentische thailändische Küche in Chur",
      openingHours: ({
        monday: { open: "11:30", close: "14:00" },
        tuesday: { open: "11:30", close: "14:00" },
        wednesday: { open: "11:30", close: "14:00" },
        thursday: { open: "11:30", close: "14:00" },
        friday: { open: "11:30", close: "14:00" },
        saturday: { open: "17:00", close: "22:00" },
      }),
      closedDays: (["sunday"]),
      openingHoursText: "Abends Mo-Fr 17:00-22:00",
      vegetarianOptions: true,
      veganOptions: true,
      glutenFreeOptions: true,
      isPublished: true,
      isFeatured: false,
    },
    {
      name: "Gasthaus Marsöl",
      slug: "gasthaus-marsoel",
      address: "Süsswinkelgasse 25",
      city: "Chur",
      postalCode: "7000",
      phone: "+41 81 252 97 68",
      website: "https://www.marsoel.ch",
      cuisineTypes: (["Schweizerisch", "Bündner Spezialitäten"]),
      priceLevel: "$$",
      descriptionDe: "Das Gasthaus Marsöl bietet gutbürgerliche Bündner Küche in familiärer Atmosphäre. Beliebt bei Einheimischen und Gästen gleichermassen.",
      shortDescDe: "Gutbürgerliche Bündner Küche in familiärer Atmosphäre",
      openingHours: ({
        monday: { open: "11:30", close: "14:00" },
        tuesday: { open: "11:30", close: "14:00" },
        wednesday: { open: "11:30", close: "14:00" },
        thursday: { open: "11:30", close: "14:00" },
        friday: { open: "11:30", close: "14:00" },
        saturday: { open: "11:30", close: "14:00" },
      }),
      closedDays: (["sunday"]),
      openingHoursText: "Abends Mo-Sa 17:30-21:30",
      vegetarianOptions: true,
      isPublished: true,
      isFeatured: false,
    },
    {
      name: "Café Arcas",
      slug: "cafe-arcas",
      address: "Arcas 12",
      city: "Chur",
      postalCode: "7000",
      phone: "+41 81 252 13 13",
      cuisineTypes: (["Café/Bistro", "International"]),
      priceLevel: "$",
      descriptionDe: "Das Café Arcas ist ein beliebter Treffpunkt am Arcasplatz. Frühstück, Mittagsmenü und hausgemachte Kuchen in entspannter Atmosphäre.",
      shortDescDe: "Beliebtes Café am Arcasplatz mit hausgemachten Kuchen",
      openingHours: ({
        monday: { open: "07:30", close: "18:00" },
        tuesday: { open: "07:30", close: "18:00" },
        wednesday: { open: "07:30", close: "18:00" },
        thursday: { open: "07:30", close: "18:00" },
        friday: { open: "07:30", close: "18:00" },
        saturday: { open: "08:00", close: "17:00" },
      }),
      closedDays: (["sunday"]),
      vegetarianOptions: true,
      veganOptions: true,
      outdoorSeating: true,
      terrace: true,
      wheelchairAccessible: true,
      isPublished: true,
      isFeatured: false,
    },
    {
      name: "Stern Restaurant",
      slug: "stern-restaurant",
      address: "Reichsgasse 11",
      city: "Chur",
      postalCode: "7000",
      phone: "+41 81 258 57 57",
      website: "https://www.stern-chur.ch",
      cuisineTypes: (["Schweizerisch", "Französisch", "International"]),
      priceLevel: "$$$",
      descriptionDe: "Das preisgekrönte Restaurant im Romantik Hotel Stern bietet gehobene Küche mit regionalen und saisonalen Produkten. Ein kulinarisches Highlight in Chur.",
      shortDescDe: "Gehobene Küche im historischen Romantik Hotel Stern",
      openingHours: ({
        tuesday: { open: "12:00", close: "14:00" },
        wednesday: { open: "12:00", close: "14:00" },
        thursday: { open: "12:00", close: "14:00" },
        friday: { open: "12:00", close: "14:00" },
        saturday: { open: "18:00", close: "22:00" },
      }),
      closedDays: (["sunday", "monday"]),
      openingHoursText: "Abends Di-Fr 18:00-22:00",
      vegetarianOptions: true,
      reservationRequired: true,
      menuUrl: "https://www.stern-chur.ch/restaurant",
      isPublished: true,
      isFeatured: true,
    },
    {
      name: "Tandoori Masala",
      slug: "tandoori-masala",
      address: "Quaderstrasse 18",
      city: "Chur",
      postalCode: "7000",
      phone: "+41 81 250 30 30",
      cuisineTypes: (["Indisch", "Asiatisch"]),
      priceLevel: "$$",
      descriptionDe: "Tandoori Masala bringt die Aromen Indiens nach Chur. Authentische Currys, Tandoori-Gerichte und frisch gebackenes Naan-Brot.",
      shortDescDe: "Authentische indische Küche mit Tandoori-Spezialitäten",
      openingHours: ({
        monday: { open: "11:30", close: "14:00" },
        tuesday: { open: "11:30", close: "14:00" },
        wednesday: { open: "11:30", close: "14:00" },
        thursday: { open: "11:30", close: "14:00" },
        friday: { open: "11:30", close: "14:00" },
        saturday: { open: "17:00", close: "22:30" },
        sunday: { open: "17:00", close: "22:00" },
      }),
      openingHoursText: "Abends Mo-Fr 17:00-22:30",
      vegetarianOptions: true,
      veganOptions: true,
      glutenFreeOptions: true,
      isPublished: true,
      isFeatured: false,
    },
    {
      name: "Bieraria Bündner Herrschaft",
      slug: "bieraria-buendner-herrschaft",
      address: "Kornplatz 1",
      city: "Chur",
      postalCode: "7000",
      phone: "+41 81 252 42 42",
      cuisineTypes: (["Schweizerisch", "Bündner Spezialitäten", "Bar/Lounge"]),
      priceLevel: "$$",
      descriptionDe: "Die Bieraria am Kornplatz ist ein beliebter Treffpunkt für Bierliebhaber und Freunde der Bündner Küche. Grosse Auswahl an Craft-Bieren und deftige Gerichte.",
      shortDescDe: "Craft-Bier und Bündner Küche am Kornplatz",
      openingHours: ({
        monday: { open: "10:00", close: "23:30" },
        tuesday: { open: "10:00", close: "23:30" },
        wednesday: { open: "10:00", close: "23:30" },
        thursday: { open: "10:00", close: "00:00" },
        friday: { open: "10:00", close: "01:00" },
        saturday: { open: "10:00", close: "01:00" },
        sunday: { open: "10:00", close: "22:00" },
      }),
      vegetarianOptions: true,
      outdoorSeating: true,
      terrace: true,
      wheelchairAccessible: true,
      isPublished: true,
      isFeatured: false,
    },
  ];

  for (const rest of restaurantData) {
    await db.insert(restaurants).values(rest);
  }
  console.log(`[Seed] ${restaurantData.length} Restaurants eingefügt`);
}
