import mysql from "mysql2/promise";

const hotels = [
  {
    slug: "ambiente-hotel-freieck",
    name: "Ambiente Hotel Freieck",
    type: "hotel",
    stars: 3,
    address: "Reichsgasse 44",
    postalCode: "7000",
    city: "Chur",
    shortDescription: "Charmantes Boutique-Hotel in der Altstadt mit individuell gestalteten Zimmern.",
    description: "Das Ambiente Hotel Freieck ist ein charmantes Boutique-Hotel im Herzen der Churer Altstadt.",
    phone: "+41 81 255 15 15",
    email: "info@freieck.ch",
    website: "https://www.freieck.ch",
    bookingUrl: "https://www.freieck.ch/buchen",
    priceFrom: "120",
    priceTo: "220",
    petsAllowed: false,
    familyFriendly: true,
    wheelchairAccessible: false,
    parking: false,
    wifi: true,
    breakfast: true,
    restaurant: false,
    checkInFrom: "14:00",
    checkOutUntil: "11:00"
  },
  {
    slug: "bogentrakt-hostel",
    name: "Bogentrakt Hostel",
    type: "hostel",
    stars: null,
    address: "Sennhofstrasse 19a",
    postalCode: "7000",
    city: "Chur",
    shortDescription: "Kreatives Hostel in einem historischen Gebäude.",
    description: "Das Bogentrakt Hostel befindet sich in einem liebevoll renovierten historischen Gebäude.",
    phone: "+41 81 250 50 50",
    email: "info@bogentrakt.ch",
    website: "https://www.bogentrakt.ch",
    bookingUrl: "https://www.bogentrakt.ch/buchen",
    priceFrom: "35",
    priceTo: "80",
    petsAllowed: false,
    familyFriendly: true,
    wheelchairAccessible: false,
    parking: false,
    wifi: true,
    breakfast: true,
    restaurant: false,
    checkInFrom: "15:00",
    checkOutUntil: "10:00"
  },
  {
    slug: "central-hotel-post",
    name: "Central Hotel Post",
    type: "hotel",
    stars: 3,
    address: "Poststrasse 11",
    postalCode: "7000",
    city: "Chur",
    shortDescription: "Zentral gelegenes 3-Sterne-Hotel mit Tradition und modernem Komfort.",
    description: "Das Central Hotel Post verbindet Tradition mit modernem Komfort.",
    phone: "+41 81 252 01 01",
    email: "info@central-hotel-post.ch",
    website: "https://www.central-hotel-post.ch",
    bookingUrl: "https://www.central-hotel-post.ch/buchen",
    priceFrom: "130",
    priceTo: "200",
    petsAllowed: true,
    familyFriendly: true,
    wheelchairAccessible: true,
    parking: true,
    wifi: true,
    breakfast: true,
    restaurant: true,
    checkInFrom: "14:00",
    checkOutUntil: "11:00"
  },
  {
    slug: "franziskaner-hotel-am-ochsenplatz",
    name: "Franziskaner Hotel am Ochsenplatz",
    type: "hotel",
    stars: 3,
    address: "Kupfergasse 18",
    postalCode: "7000",
    city: "Chur",
    shortDescription: "Gemütliches Hotel am malerischen Ochsenplatz mit Restaurant.",
    description: "Das Franziskaner Hotel liegt am malerischen Ochsenplatz in der Churer Altstadt.",
    phone: "+41 81 252 12 12",
    email: "info@franziskaner-chur.ch",
    website: "https://www.franziskaner-chur.ch",
    bookingUrl: "https://www.franziskaner-chur.ch/zimmer",
    priceFrom: "110",
    priceTo: "180",
    petsAllowed: true,
    familyFriendly: true,
    wheelchairAccessible: false,
    parking: false,
    wifi: true,
    breakfast: true,
    restaurant: true,
    checkInFrom: "14:00",
    checkOutUntil: "10:30"
  },
  {
    slug: "gartenhotel-sternen",
    name: "Gartenhotel Sternen",
    type: "hotel",
    stars: 3,
    address: "Via Nova 102",
    postalCode: "7013",
    city: "Domat/Ems",
    shortDescription: "Gemütliches Hotel mit grossem Garten in Domat/Ems.",
    description: "Das Gartenhotel Sternen in Domat/Ems bietet eine ruhige Oase mit grossem Garten.",
    phone: "+41 81 650 11 11",
    email: "info@gartenhotel-sternen.ch",
    website: "https://www.gartenhotel-sternen.ch",
    bookingUrl: "https://www.gartenhotel-sternen.ch/buchen",
    priceFrom: "100",
    priceTo: "160",
    petsAllowed: true,
    familyFriendly: true,
    wheelchairAccessible: true,
    parking: true,
    wifi: true,
    breakfast: true,
    restaurant: true,
    checkInFrom: "14:00",
    checkOutUntil: "10:00"
  },
  {
    slug: "hotel-abc",
    name: "Hotel ABC",
    type: "hotel",
    stars: 4,
    address: "Ottostrasse 8",
    postalCode: "7000",
    city: "Chur",
    shortDescription: "Modernes 4-Sterne-Hotel im Herzen von Chur mit erstklassigem Service.",
    description: "Das Hotel ABC ist ein modernes 4-Sterne-Hotel im Zentrum von Chur.",
    phone: "+41 81 254 13 13",
    email: "abc@hotelabc.ch",
    website: "https://www.hotelabc.ch",
    bookingUrl: "https://www.hotelabc.ch/buchen",
    priceFrom: "180",
    priceTo: "320",
    petsAllowed: true,
    familyFriendly: true,
    wheelchairAccessible: true,
    parking: true,
    wifi: true,
    breakfast: true,
    restaurant: true,
    checkInFrom: "14:00",
    checkOutUntil: "11:00"
  },
  {
    slug: "hotel-alte-post",
    name: "Hotel Alte Post",
    type: "hotel",
    stars: 4,
    address: "Versamerstrasse 1",
    postalCode: "7402",
    city: "Bonaduz",
    shortDescription: "Elegantes 4-Sterne-Hotel in Bonaduz mit Wellness und Gourmet-Küche.",
    description: "Das Hotel Alte Post in Bonaduz ist ein elegantes 4-Sterne-Hotel mit Wellness-Bereich.",
    phone: "+41 81 650 10 10",
    email: "info@hotel-alte-post.ch",
    website: "https://www.hotel-alte-post.ch",
    bookingUrl: "https://www.hotel-alte-post.ch/buchen",
    priceFrom: "200",
    priceTo: "380",
    petsAllowed: false,
    familyFriendly: true,
    wheelchairAccessible: true,
    parking: true,
    wifi: true,
    breakfast: true,
    restaurant: true,
    checkInFrom: "15:00",
    checkOutUntil: "11:00"
  },
  {
    slug: "hotel-chur",
    name: "Hotel Chur",
    type: "hotel",
    stars: 3,
    address: "Am Obertor - Welschdörfli 2",
    postalCode: "7000",
    city: "Chur",
    shortDescription: "Gemütliches 3-Sterne-Hotel am Eingang zur Altstadt.",
    description: "Das Hotel Chur befindet sich am Eingang zur historischen Altstadt.",
    phone: "+41 81 252 22 22",
    email: "info@hotelchur.ch",
    website: "https://www.hotelchur.ch",
    bookingUrl: "https://www.hotelchur.ch/buchen",
    priceFrom: "120",
    priceTo: "190",
    petsAllowed: true,
    familyFriendly: true,
    wheelchairAccessible: false,
    parking: true,
    wifi: true,
    breakfast: true,
    restaurant: true,
    checkInFrom: "14:00",
    checkOutUntil: "10:00"
  },
  {
    slug: "hotel-drei-koenige",
    name: "Hotel Drei Könige",
    type: "hotel",
    stars: 3,
    address: "Reichsgasse 18",
    postalCode: "7000",
    city: "Chur",
    shortDescription: "Historisches Gasthaus in der Altstadt mit traditionellem Charme.",
    description: "Das Hotel Drei Könige ist ein historisches Gasthaus im Herzen der Churer Altstadt.",
    phone: "+41 81 252 17 25",
    email: "info@dreikoenige-chur.ch",
    website: "https://www.dreikoenige-chur.ch",
    bookingUrl: "https://www.dreikoenige-chur.ch/zimmer",
    priceFrom: "100",
    priceTo: "170",
    petsAllowed: false,
    familyFriendly: true,
    wheelchairAccessible: false,
    parking: false,
    wifi: true,
    breakfast: true,
    restaurant: true,
    checkInFrom: "14:00",
    checkOutUntil: "10:00"
  },
  {
    slug: "hotel-ibis-chur",
    name: "Hotel Ibis Chur",
    type: "hotel",
    stars: 2,
    address: "Richtstrasse 19",
    postalCode: "7000",
    city: "Chur",
    shortDescription: "Budget-freundliches Hotel der Accor-Gruppe.",
    description: "Das Hotel Ibis Chur bietet funktionale Zimmer zu günstigen Preisen.",
    phone: "+41 81 354 80 00",
    email: "h7475@accor.com",
    website: "https://www.accorhotels.com/ibis-chur",
    bookingUrl: "https://www.accorhotels.com/ibis-chur/buchen",
    priceFrom: "89",
    priceTo: "140",
    petsAllowed: true,
    familyFriendly: true,
    wheelchairAccessible: true,
    parking: true,
    wifi: true,
    breakfast: true,
    restaurant: false,
    checkInFrom: "12:00",
    checkOutUntil: "12:00"
  },
  {
    slug: "hotel-rosenhuegel",
    name: "Hotel Rosenhügel",
    type: "hotel",
    stars: 3,
    address: "Malixerstrasse 32",
    postalCode: "7000",
    city: "Chur",
    shortDescription: "Ruhiges Hotel mit Aussicht auf die Bündner Berge.",
    description: "Das Hotel Rosenhügel liegt in ruhiger Lage mit herrlicher Aussicht.",
    phone: "+41 81 252 10 52",
    email: "info@rosenhuegel.ch",
    website: "https://www.rosenhuegel.ch",
    bookingUrl: "https://www.rosenhuegel.ch/buchen",
    priceFrom: "110",
    priceTo: "180",
    petsAllowed: true,
    familyFriendly: true,
    wheelchairAccessible: false,
    parking: true,
    wifi: true,
    breakfast: true,
    restaurant: true,
    checkInFrom: "14:00",
    checkOutUntil: "10:00"
  },
  {
    slug: "hotel-sommerau",
    name: "Hotel Sommerau",
    type: "hotel",
    stars: 3,
    address: "Emserstrasse 4",
    postalCode: "7000",
    city: "Chur",
    shortDescription: "Ruhig gelegenes 3-Sterne-Hotel mit Garten.",
    description: "Das Hotel Sommerau bietet eine ruhige Lage mit schönem Garten.",
    phone: "+41 81 252 36 44",
    email: "info@hotelsommerau.ch",
    website: "https://www.hotelsommerau.ch",
    bookingUrl: "https://www.hotelsommerau.ch/buchen",
    priceFrom: "115",
    priceTo: "185",
    petsAllowed: true,
    familyFriendly: true,
    wheelchairAccessible: true,
    parking: true,
    wifi: true,
    breakfast: true,
    restaurant: true,
    checkInFrom: "14:00",
    checkOutUntil: "10:00"
  },
  {
    slug: "hotel-sportcenter-fuenf-doerfer",
    name: "Hotel Sportcenter Fünf Dörfer",
    type: "hotel",
    stars: 3,
    address: "Oberauweg 186D",
    postalCode: "7205",
    city: "Zizers",
    shortDescription: "Sporthotel mit Fitnessanlagen und Tennisplätzen.",
    description: "Das Hotel Sportcenter Fünf Dörfer ist ideal für sportbegeisterte Gäste.",
    phone: "+41 81 322 55 55",
    email: "info@sportcenter5d.ch",
    website: "https://www.sportcenter5d.ch",
    bookingUrl: "https://www.sportcenter5d.ch/hotel",
    priceFrom: "95",
    priceTo: "160",
    petsAllowed: false,
    familyFriendly: true,
    wheelchairAccessible: true,
    parking: true,
    wifi: true,
    breakfast: true,
    restaurant: true,
    checkInFrom: "14:00",
    checkOutUntil: "10:00"
  },
  {
    slug: "hotel-stern-chur",
    name: "Hotel Stern Chur",
    type: "hotel",
    stars: 4,
    address: "Reichsgasse 11",
    postalCode: "7000",
    city: "Chur",
    shortDescription: "Traditionsreiches 4-Sterne-Hotel in der historischen Altstadt.",
    description: "Das Hotel Stern Chur ist ein traditionsreiches 4-Sterne-Hotel in der Altstadt.",
    phone: "+41 81 258 57 57",
    email: "info@stern-chur.ch",
    website: "https://www.stern-chur.ch",
    bookingUrl: "https://www.stern-chur.ch/buchen",
    priceFrom: "190",
    priceTo: "350",
    petsAllowed: false,
    familyFriendly: true,
    wheelchairAccessible: true,
    parking: true,
    wifi: true,
    breakfast: true,
    restaurant: true,
    checkInFrom: "14:00",
    checkOutUntil: "11:00"
  },
  {
    slug: "malixerhof",
    name: "Malixerhof",
    type: "hotel",
    stars: 3,
    address: "Brambrüeschstrasse 204",
    postalCode: "7074",
    city: "Malix",
    shortDescription: "Berghotel mit Panoramablick auf die Bündner Alpen.",
    description: "Der Malixerhof ist ein charmantes Berghotel mit atemberaubendem Panoramablick.",
    phone: "+41 81 252 12 62",
    email: "info@malixerhof.ch",
    website: "https://www.malixerhof.ch",
    bookingUrl: "https://www.malixerhof.ch/buchen",
    priceFrom: "100",
    priceTo: "170",
    petsAllowed: true,
    familyFriendly: true,
    wheelchairAccessible: false,
    parking: true,
    wifi: true,
    breakfast: true,
    restaurant: true,
    checkInFrom: "14:00",
    checkOutUntil: "10:00"
  },
  {
    slug: "mercure-chur-city-west",
    name: "Mercure Chur City West",
    type: "hotel",
    stars: 4,
    address: "Comercialstrasse 32",
    postalCode: "7000",
    city: "Chur",
    shortDescription: "Internationales 4-Sterne-Hotel der Accor-Gruppe.",
    description: "Das Mercure Chur City West ist ein modernes 4-Sterne-Hotel der Accor-Gruppe.",
    phone: "+41 81 354 85 85",
    email: "h7476@accor.com",
    website: "https://www.accorhotels.com/mercure-chur",
    bookingUrl: "https://www.accorhotels.com/mercure-chur/buchen",
    priceFrom: "150",
    priceTo: "280",
    petsAllowed: true,
    familyFriendly: true,
    wheelchairAccessible: true,
    parking: true,
    wifi: true,
    breakfast: true,
    restaurant: true,
    checkInFrom: "14:00",
    checkOutUntil: "12:00"
  },
  {
    slug: "swiss-heidi-hotel",
    name: "Swiss Heidi Hotel",
    type: "hotel",
    stars: 3,
    address: "Werkhofstrasse 1",
    postalCode: "7304",
    city: "Maienfeld",
    shortDescription: "Familienfreundliches Hotel im Heidiland.",
    description: "Das Swiss Heidi Hotel in Maienfeld liegt im berühmten Heidiland.",
    phone: "+41 81 330 30 30",
    email: "info@swissheidihotel.ch",
    website: "https://www.swissheidihotel.ch",
    bookingUrl: "https://www.swissheidihotel.ch/buchen",
    priceFrom: "120",
    priceTo: "220",
    petsAllowed: true,
    familyFriendly: true,
    wheelchairAccessible: true,
    parking: true,
    wifi: true,
    breakfast: true,
    restaurant: true,
    checkInFrom: "14:00",
    checkOutUntil: "10:00"
  },
  {
    slug: "viva-hostel",
    name: "VIVA Hostel",
    type: "hostel",
    stars: null,
    address: "Welschdörfli 19",
    postalCode: "7000",
    city: "Chur",
    shortDescription: "Modernes Hostel für Backpacker und Budget-Reisende.",
    description: "Das VIVA Hostel ist ein modernes Hostel für Backpacker und Budget-Reisende.",
    phone: "+41 81 252 60 60",
    email: "info@vivahostel.ch",
    website: "https://www.vivahostel.ch",
    bookingUrl: "https://www.vivahostel.ch/buchen",
    priceFrom: "30",
    priceTo: "70",
    petsAllowed: false,
    familyFriendly: true,
    wheelchairAccessible: false,
    parking: false,
    wifi: true,
    breakfast: true,
    restaurant: false,
    checkInFrom: "15:00",
    checkOutUntil: "10:00"
  },
  {
    slug: "zunfthaus-zur-rebleuten",
    name: "Zunfthaus zur Rebleuten",
    type: "pension",
    stars: null,
    address: "Pfisterplatz 1",
    postalCode: "7000",
    city: "Chur",
    shortDescription: "Historisches Zunfthaus mit Gästezimmern und Restaurant.",
    description: "Das Zunfthaus zur Rebleuten ist ein historisches Gebäude mit Gästezimmern.",
    phone: "+41 81 252 13 13",
    email: "info@rebleuten.ch",
    website: "https://www.rebleuten.ch",
    bookingUrl: "https://www.rebleuten.ch/zimmer",
    priceFrom: "90",
    priceTo: "150",
    petsAllowed: false,
    familyFriendly: true,
    wheelchairAccessible: false,
    parking: false,
    wifi: true,
    breakfast: true,
    restaurant: true,
    checkInFrom: "14:00",
    checkOutUntil: "10:00"
  }
];

async function seed() {
  const connection = await mysql.createConnection(process.env.DATABASE_URL);
  
  console.log("Seeding hotels...");
  
  for (const hotel of hotels) {
    try {
      const sql = `INSERT INTO hotels (slug, name, type, stars, address, postalCode, city, shortDescription, description, phone, email, website, bookingUrl, priceFrom, priceTo, petsAllowed, familyFriendly, wheelchairAccessible, parking, wifi, breakfast, restaurant, checkInFrom, checkOutUntil, isActive)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ON DUPLICATE KEY UPDATE name = VALUES(name)`;
      
      await connection.execute(sql, [
        hotel.slug, hotel.name, hotel.type, hotel.stars, hotel.address, hotel.postalCode, hotel.city,
        hotel.shortDescription, hotel.description, hotel.phone, hotel.email, hotel.website, hotel.bookingUrl,
        hotel.priceFrom, hotel.priceTo, hotel.petsAllowed ? 1 : 0, hotel.familyFriendly ? 1 : 0,
        hotel.wheelchairAccessible ? 1 : 0, hotel.parking ? 1 : 0, hotel.wifi ? 1 : 0, hotel.breakfast ? 1 : 0,
        hotel.restaurant ? 1 : 0, hotel.checkInFrom, hotel.checkOutUntil, 1
      ]);
      console.log("✓ " + hotel.name);
    } catch (error) {
      console.error("✗ " + hotel.name + ": " + error.message);
    }
  }
  
  console.log("\nSeeding complete!");
  await connection.end();
}

seed().catch(console.error);
